Detect merged branches. Affects #28.
robertdfrench/git-pr pull request #35
Opened 2021-10-14 18:45 UTC by robertdfrench

This ensures we can test for "merged branches", which will subsequently be deleted as part of `pr-clean`.

2021-10-14 22:04 UTC, robertdfrench commented
@calebwherry this PR uses the same testing patterns as #24, so if you don't like those, you might not like these either. I'm starting to have some concerns myself that `fake_git` does not serve any real purpose.

2021-10-15 14:27 UTC, calebwherry commented on src/lib.rs
> +        let path = String::from("./target/release/fake_git");
Needs to be updated with new functionality on trunk.

2021-10-15 14:27 UTC, calebwherry commented on src/lib.rs
> +        let path = String::from("./target/release/fake_git");
SAA

2021-10-15 14:28 UTC, calebwherry commented on src/lib.rs
> +        merged_branches.push_str("\n");
Why can't this be the last element in the vec?

2021-10-15 14:29 UTC, calebwherry commented on tests/real_git.rs
> +    println!("TempDir='{:?}'", TEST_STATE.path());
Would be nice to push this into a macro I think to hide "touching" of tempdir. Maybe "init_test_state"? Or something like that.

2021-10-15 14:29 UTC, calebwherry commented on tests/real_git.rs
> +    println!("TempDir='{:?}'", TEST_STATE.path());
Would be nice to push this into a macro I think to hide "touching" of tempdir. Maybe "init_test_state"? Or something like that.

2021-10-15 14:31 UTC, calebwherry requested changes
Reviewed.

2021-10-15 14:37 UTC, calebwherry commented on tests/real_git.rs
> +    println!("TempDir='{:?}'", TEST_STATE.path());
Created #40 to address this.

2021-10-15 17:24 UTC, calebwherry commented on src/lib.rs
> +        merged_branches.push_str("\n");
Fixed in 63af7c6

2021-10-15 17:25 UTC, calebwherry commented on src/lib.rs
> +        let path = String::from("./target/release/fake_git");
Fixed in 3ce3a48

2021-10-15 17:25 UTC, calebwherry commented on src/lib.rs
> +        let path = String::from("./target/release/fake_git");
Fixed in 3ce3a48

2021-10-15 17:27 UTC, calebwherry approved these changes

2021-10-15 17:27 UTC, merged